version: '2'

services:
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    volumes:
      - ./application:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.test
