version: '2'

services:
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    volumes:
      - ./application:/app
    environment:
      - RAILS_ENV=development
    depends_on:
      - db
      - mail

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  db:
    extends:
      file: docker-compose.common.yml
      service: db
    ports:
      - 5432:5432


volumes:
  db-data:
    driver: local
