version: '2'

services:
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    env_file:
      - config.env
    depends_on:
      - db
    command: ./entrypoints/prod.sh
    restart: always

  db:
    extends:
      file: docker-compose.common.yml
      service: db
    restart: always


volumes:
  db-data:
    driver: local
