version: '2'

services:

  web:
    build: ./application
    ports:
      - 8000:3000

  db:
    image: postgres:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/


volumes:
  db-data:
    driver: local
